/**
 * Build information for the application.
 * Auto-generated by scripts/increment-build.js on each build.
 */
export interface BuildInfo {
  buildNumber: number;
  version: string;
  timestamp: string;
}

let buildInfo: BuildInfo | null = null;

/**
 * Fetch build info from the server.
 * Cached after first call.
 */
export async function getBuildInfo(): Promise<BuildInfo> {
  if (buildInfo) return buildInfo;
  
  try {
    const response = await fetch('/build-info.json');
    buildInfo = await response.json();
    return buildInfo!;
  } catch (err) {
    console.warn('Failed to load build info:', err);
    // Dev mode fallback
    return {
      buildNumber: 0,
      version: '1.0.0-dev',
      timestamp: new Date().toISOString()
    };
  }
}

/**
 * Format build info as a display string.
 * Example: "v1.0.0 #42 · May 12, 2026"
 */
export function formatBuildInfo(info: BuildInfo): string {
  const date = info.timestamp ? new Date(info.timestamp).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  }) : '';
  return `v${info.version} #${info.buildNumber}${date ? ' · ' + date : ''}`;
}
