/**
 * Build information for the application.
 * Auto-generated by scripts/increment-build.js on each build.
 */
export interface BuildInfo {
  buildNumber: number;
  version: string;
  timestamp: string;
}

let buildInfo: BuildInfo | null = null;

/**
 * Fetch build info from the server.
 * Cached after first call.
 */
export async function getBuildInfo(): Promise<BuildInfo> {
  if (buildInfo) return buildInfo;
  
  try {
    const response = await fetch('/build-info.json');
    buildInfo = await response.json();
    return buildInfo!;
  } catch (err) {
    console.warn('Failed to load build info:', err);
    return { buildNumber: 0, version: '1.0.0', timestamp: '' };
  }
}

/**
 * Format build info as a display string.
 * Example: "v1.0.0 (build 42)"
 */
export function formatBuildInfo(info: BuildInfo): string {
  return `v${info.version} (build ${info.buildNumber})`;
}
